//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiplication_tables_web_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Grade_Table_1 { get; set; }
        public string Grade_Table_2 { get; set; }
        public string Grade_Table_3 { get; set; }
        public string Grade_Table_4 { get; set; }
        public string Grade_Table_5 { get; set; }
        public string Grade_Table_6 { get; set; }
        public string Grade_Table_7 { get; set; }
        public string Grade_Table_8 { get; set; }
        public string Grade_Table_9 { get; set; }
        public string Grade_Table_10 { get; set; }
        public string Grade_Final { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
