//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiplication_tables_web_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestName
    {
        public int TestID { get; set; }
        public string Name { get; set; }
    }
}
